spring.application.name=MovieRentalSystem

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Server port
server.port=8080

tmdb.api.key=a9facc7e7b5e8f0f04900ff176a2c0fc